version: "3.9"

volumes:
  php-var:
    name:
      symfony-study-3_volume-php-var
  php-vendor:
    name:
      symfony-study-3_volume-php-vendor

services:
  php:
    build: 
      context: .
      dockerfile: dockerfile
    image: symfony-study-3_php:latest
    container_name: php
    volumes: 
      - ./config/ini:/usr/local/etc/php
      - .:/var/www/html
      - php-var:/var/www/html/var       # Для того, чтобы папка не сбрасывалась после запуска конфигурации Docker-Compose
      - php-vendor:/var/www/html/vendor # Для того, чтобы папка не сбрасывалась после запуска конфигурации Docker-Compose
    networks:
      - network

  nginx:
    image: nginx:1.21.1
    container_name: nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - network

networks:
  network:
    name: symfony-study-3_network