version: "3.9"

volumes:
  php-var:
    name:
      ${APP_NAME}_volume-php-var
  php-vendor:
    name:
      ${APP_NAME}_volume-php-vendor

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - "APP_ROOT=${APP_ROOT}"
    image: ${APP_NAME}_image-php:latest
    container_name: ${APP_NAME}_container-php
    volumes: 
      - .:${APP_ROOT}
      - php-var:${APP_ROOT}/var             # Для того, чтобы папка не сбрасывалась после запуска конфигурации Docker-Compose
      - php-vendor:${APP_ROOT}/vendor       # Для того, чтобы папка не сбрасывалась после запуска конфигурации Docker-Compose
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - network

  nginx:
    image: nginx:1.21.1
    container_name: ${APP_NAME}_container-nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - network

networks:
  network:
    name: ${APP_NAME}_network