version: "3.9"

services:
  php-apache:
    build: 
      context: ./php
      dockerfile: Dockerfile
    image: symfony-study-3/php-apache:latest
    container_name: php-apache
    ports: 
      - 80:80