version: "3.9"

volumes:
  php-var:
    name:
      ${APP_NAME}_volume-php-var
  php-vendor:
    name:
      ${APP_NAME}_volume-php-vendor

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - "APP_ROOT=${APP_ROOT}"
    image: ${APP_NAME}_image-php:latest
    container_name: ${APP_NAME}_container-php
    volumes: 
      - .:${APP_ROOT}
      - php-var:${APP_ROOT}/var             # Для того, чтобы папка не сбрасывалась после запуска конфигурации Docker-Compose
      - php-vendor:${APP_ROOT}/vendor       # Для того, чтобы папка не сбрасывалась после запуска конфигурации Docker-Compose
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - network

  nginx:
    image: nginx:1.21.1
    container_name: ${APP_NAME}_container-nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${SERVER_PORT}:80
    depends_on:
      - php
      - postgres
    networks:
      - network

  postgres:
    image: postgres:13.4-buster
    container_name: ${APP_NAME}_container-postgres
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - network

networks:
  network:
    name: ${APP_NAME}_network